name: Decrypt Secrets

on:
  workflow_dispatch:

jobs:
  decrypt-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install SOPS
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.9.1/sops-v3.9.1.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: List files
        run: ls -l

      - name: Make decrypt-secrets.sh executable
        run: chmod +x .github/workflows/decrypt-secrets.sh

      - name: Decrypt secrets.json
        run: .github/workflows/decrypt-secrets.sh

      - name: Upload decrypted secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets-dec
          path: secrets.dec.json