name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      aws_user:
        description: 'AWS IAM user/role (default: github-actions-user)'
        required: false
        default: 'Charles'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_USER: ${{ github.event.inputs.aws_user }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Download Terraform Plan from S3
        run: |
          aws s3 cp s3://terraformplans-logservice/${{ env.ENVIRONMENT }}/plan.tfplan plan.tfplan

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan