name: Encrypt API Key

on:
  workflow_dispatch:
    inputs:
      api_key_name:
        description: 'Name of the API key (e.g., STRIPE_KEY)'
        required: true

jobs:
  encrypt-api-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SOPS
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.9.1/sops-v3.9.1.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Create plaintext secrets.json
        env:
          API_KEY_NAME: ${{ github.event.inputs.api_key_name }}
        run: |
          echo "Creating secrets.json with key: $API_KEY_NAME"
          echo "{\"$API_KEY_NAME\": \"dummy-value-replace-this\"}" > secrets.json
          cat secrets.json

      - name: Encrypt secrets.json with SOPS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          sops --encrypt \
            --kms "arn:aws:kms:eu-north-1:764678966183:key/a6155e20-0862-4d84-8457-b2b43be79b64" \
            secrets.json > secrets.enc.json

      - name: Upload encrypted secret to S3
        run: |
          aws s3 cp secrets.enc.json s3://logservicprojectbucketfile/secrets.enc.json