name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      aws_user:
        description: 'AWS IAM user/role (default: github-actions-user)'
        required: false
        default: 'github-actions-user'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_USER: ${{ github.event.inputs.aws_user }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7
      
      - name: Install SOPS
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux
          mv sops /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

      - name: Zip Lambda code
        run: zip lambda.zip lambda/handler.py

      - name: Update CA Certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates
     
      - name: Debug Environment
        run: env | grep AWS

      - name: Terraform Init
        run: terraform init
      

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ env.ENVIRONMENT }}" -var="sops_user_arn=arn:aws:iam::764678966183:user/${{ env.AWS_USER }}" -out=plan.tfplan
        env:
          AWS_SDK_LOAD_CONFIG: true
          AWS_PROFILE: ${{ env.AWS_USER }}
          SOPS_KMS_PG: arn:aws:kms:eu-north-1:764678966183:key/a6155e20-0862-4d84-8457-b2b43be79b64
        
      - name: Save Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ env.ENVIRONMENT }}-latest
          path: plan.tfplan
