name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      aws_user:
        description: 'AWS IAM user/role (default: github-actions-user)'
        required: false
        default: 'Charles'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_USER: ${{ github.event.inputs.aws_user }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SOPS
        run: |
          curl -Lo sops https://github.com/mozilla/sops/releases/download/v3.9.1/sops-v3.9.1.linux.amd64
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Download encrypted secrets
        uses: actions/download-artifact@v4
        with:
          name: sopsencryptedsecret
          path: .

      - name: Decrypt secrets
        run: |
          sops -d secrets.enc.json > secrets.dec.json
          cat secrets.dec.json

      - name: Upload decrypted secrets
        uses: actions/upload-artifact@v4
        with:
          name: secrets-dec
          path: secrets.dec.json

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: List files (debug)
        run: ls -l

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ env.ENVIRONMENT }}" -out=plan.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ env.ENVIRONMENT }}-latest
          path: plan.tfplan

      - name: Delete decrypted secrets
        run: rm -f secrets.dec.json